#Spring Data JPA
spring.datasource.url=${POSTGRES_URL}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=security
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.platform=postgres

logging.level.org.springframework.security.web.*=debug